### ISSUE TITLE
Quadro P1000 not detected

### ISSUE THREAD

**Issue by kenweade** [JeremyMain/GPUProfiler#135] opened 2020-01-30 18:56 UTC
Quadro P1000 not detected
<img width="907" alt="quadrop1000error" src="https://user-images.githubusercontent.com/60484409/73480604-cbe5a380-435f-11ea-95d4-e3743c4546a1.PNG">
<img width="907" alt="quadrop1000error" src="https://user-images.githubusercontent.com/60484409/73480629-db64ec80-435f-11ea-81b5-9a0db2e0aa46.PNG">

**Comment by JeremyMain** [comment] 2020-02-05 00:47
@kenweade 
This is a duplicate of #122 
Since I am unable to release the next version v1.07b until it is feature complete, I will release a bug fix version of v1.07a as v1.07a1 after back-porting the fix for this issue.

**Closed by JeremyMain** 2020-02-05 00:47 UTC

**Comment by JeremyMain** [comment] 2020-02-05 13:39
@kenweade 
A version that contains the DCH driver fix has been been posted.
https://github.com/JeremyMain/GPUProfiler/releases
